[package]
name = "phys_mem"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
global_types = { path = "../global_types" }
errchain     = { path = "../errchain" }
